#include <stdio.h>
#include "ft_malloc.h"

void show(char *str)
{
	static int b = 0;
	if (b)
		write(1, "\n", 1);

	write(1, str, strlen(str));
	show_alloc_mem();

	b = 1;
}

int main()
{
	void *ptr;
	ptr = malloc(472);
	ptr = malloc(120);
	ptr = malloc(1024);
	ptr = malloc(5);
	ptr = malloc(472);
	ptr = malloc(4096);
	ptr = malloc(5);
	ptr = malloc(47);
	ptr = malloc(47);
	ptr = malloc(104);
	ptr = malloc(42);
	ptr = malloc(72);
	ptr = malloc(36);
	ptr = malloc(56);
	ptr = malloc(41);
	ptr = malloc(72);
	ptr = malloc(36);
	ptr = malloc(36);
	ptr = malloc(192);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(44);
	ptr = malloc(44);
	ptr = malloc(104);
	ptr = malloc(39);
	ptr = malloc(72);
	ptr = malloc(33);
	ptr = malloc(56);
	ptr = malloc(38);
	ptr = malloc(72);
	ptr = malloc(33);
	ptr = malloc(33);
	ptr = malloc(80);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(42);
	ptr = malloc(42);
	ptr = malloc(104);
	ptr = malloc(37);
	ptr = malloc(72);
	ptr = malloc(31);
	ptr = malloc(56);
	ptr = malloc(36);
	ptr = malloc(72);
	ptr = malloc(31);
	ptr = malloc(31);
	ptr = malloc(104);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(40);
	ptr = malloc(40);
	ptr = malloc(104);
	ptr = malloc(35);
	ptr = malloc(72);
	ptr = malloc(29);
	ptr = malloc(56);
	ptr = malloc(34);
	ptr = malloc(72);
	ptr = malloc(29);
	ptr = malloc(29);
	ptr = malloc(168);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(37);
	ptr = malloc(37);
	ptr = malloc(104);
	ptr = malloc(32);
	ptr = malloc(72);
	ptr = malloc(26);
	ptr = malloc(56);
	ptr = malloc(31);
	ptr = malloc(72);
	ptr = malloc(26);
	ptr = malloc(26);
	ptr = malloc(120);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(38);
	ptr = malloc(38);
	ptr = malloc(104);
	ptr = malloc(33);
	ptr = malloc(72);
	ptr = malloc(27);
	ptr = malloc(56);
	ptr = malloc(32);
	ptr = malloc(72);
	ptr = malloc(27);
	ptr = malloc(27);
	ptr = malloc(88);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(41);
	ptr = malloc(41);
	ptr = malloc(104);
	ptr = malloc(36);
	ptr = malloc(72);
	ptr = malloc(30);
	ptr = malloc(56);
	ptr = malloc(41);
	ptr = malloc(56);
	ptr = malloc(41);
	ptr = malloc(47);
	ptr = malloc(72);
	ptr = malloc(41);
	ptr = malloc(47);
	ptr = malloc(41);
	ptr = malloc(41);
	ptr = malloc(35);
	ptr = malloc(72);
	ptr = malloc(30);
	ptr = malloc(46);
	ptr = malloc(72);
	ptr = malloc(41);
	ptr = malloc(46);
	ptr = malloc(41);
	ptr = malloc(41);
	ptr = malloc(30);
	ptr = malloc(52);
	ptr = malloc(104);
	ptr = malloc(47);
	ptr = malloc(46);
	ptr = malloc(41);
	ptr = malloc(52);
	ptr = malloc(47);
	ptr = malloc(46);
	ptr = malloc(41);
	ptr = malloc(47);
	ptr = malloc(46);
	ptr = malloc(41);
	ptr = malloc(104);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(41);
	ptr = malloc(41);
	ptr = malloc(104);
	ptr = malloc(36);
	ptr = malloc(72);
	ptr = malloc(30);
	ptr = malloc(56);
	ptr = malloc(35);
	ptr = malloc(72);
	ptr = malloc(30);
	ptr = malloc(30);
	ptr = malloc(432);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(40);
	ptr = malloc(40);
	ptr = malloc(104);
	ptr = malloc(35);
	ptr = malloc(72);
	ptr = malloc(29);
	ptr = malloc(56);
	ptr = malloc(34);
	ptr = malloc(72);
	ptr = malloc(29);
	ptr = malloc(29);
	ptr = malloc(216);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(37);
	ptr = malloc(37);
	ptr = malloc(104);
	ptr = malloc(32);
	ptr = malloc(72);
	ptr = malloc(26);
	ptr = malloc(56);
	ptr = malloc(31);
	ptr = malloc(72);
	ptr = malloc(26);
	ptr = malloc(26);
	ptr = malloc(1336);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(40);
	ptr = malloc(40);
	ptr = malloc(104);
	ptr = malloc(35);
	ptr = malloc(72);
	ptr = malloc(29);
	ptr = malloc(56);
	ptr = malloc(34);
	ptr = malloc(72);
	ptr = malloc(29);
	ptr = malloc(29);
	ptr = malloc(112);
	ptr = malloc(8);
	ptr = malloc(8);
	ptr = malloc(5);
	ptr = malloc(5);
	ptr = malloc(38);
	ptr = malloc(38);
	ptr = malloc(104);
	ptr = malloc(33);
	ptr = malloc(72);
	ptr = malloc(27);
	show_alloc_mem();

	t_zone *zone = g_zones;
	t_zone *tmp;
	while (zone)
	{
		tmp = zone->next;
		munmap(zone, zone->size);
		zone = tmp;
	}
	return (0);
}
